<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simplepetrinetTrace" nsURI="simplepetrinetTrace" nsPrefix="simplepetrinetTrace">
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Simplepetrinet_Net_Initialize_Sequence"
        upperBound="-1" eType="#//Steps/Simplepetrinet_Net_Initialize"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Simplepetrinet_Transition_Fire_Sequence"
        upperBound="-1" eType="#//Steps/Simplepetrinet_Transition_Fire"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootSteps" upperBound="-1"
        eType="#//Steps/Step" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simplepetrinet_tracedPlaces"
        ordered="false" upperBound="-1" eType="#//States/simplepetrinet/TracedPlace"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statesTrace" upperBound="-1"
        eType="#//States/State" containment="true"/>
  </eClassifiers>
  <eSubpackages name="Steps" nsURI="simplepetrinetTrace_Steps" nsPrefix="events">
    <eClassifiers xsi:type="ecore:EClass" name="BigStep" abstract="true" eSuperTypes="#//Steps/Step"/>
    <eClassifiers xsi:type="ecore:EClass" name="RootImplicitStep" eSuperTypes="#//Steps/SmallStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Simplepetrinet_Net_Initialize" eSuperTypes="#//Steps/SmallStep">
      <eOperations name="getCaller" lowerBound="1" eType="ecore:EClass ../../fr.inria.diverse.sample.simplepetrinet.model/model/simplepetrinet.ecore#//Net">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (Net) this.getMse().getCaller();&#xA;"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Simplepetrinet_Transition_Fire" eSuperTypes="#//Steps/SmallStep">
      <eOperations name="getCaller" lowerBound="1" eType="ecore:EClass ../../fr.inria.diverse.sample.simplepetrinet.model/model/simplepetrinet.ecore#//Transition">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (Transition) this.getMse().getCaller();&#xA;"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmallStep" abstract="true" eSuperTypes="#//Steps/Step"/>
    <eClassifiers xsi:type="ecore:EClass" name="Step" abstract="true" eSuperTypes="../../org.gemoc.executionframework.engine.mse.model/model/GemocExecutionEngineMSE.ecore#//MSEOccurrence">
      <eStructuralFeatures xsi:type="ecore:EReference" name="endingState" eType="#//States/State"
          eOpposite="#//States/State/endedSteps"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1"
          eType="#//States/State" eOpposite="#//States/State/startedSteps"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="States" nsURI="simplepetrinetTrace_States" nsPrefix="tracedclasses">
    <eClassifiers xsi:type="ecore:EClass" name="Place_tokens_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//States/simplepetrinet/TracedPlace" eOpposite="#//States/simplepetrinet/TracedPlace/tokensSequence"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
          upperBound="-1" eType="#//States/State" eOpposite="#//States/State/place_tokens_Values"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokens" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eStructuralFeatures xsi:type="ecore:EReference" name="endedSteps" upperBound="-1"
          eType="#//Steps/Step" eOpposite="#//Steps/Step/endingState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="place_tokens_Values"
          ordered="false" upperBound="-1" eType="#//States/Place_tokens_Value" eOpposite="#//States/Place_tokens_Value/states"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startedSteps" upperBound="-1"
          eType="#//Steps/Step" eOpposite="#//Steps/Step/startingState"/>
    </eClassifiers>
    <eSubpackages name="simplepetrinet" nsURI="simplepetrinetTrace_simplepetrinet"
        nsPrefix="">
      <eClassifiers xsi:type="ecore:EClass" name="TracedPlace">
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../../fr.inria.diverse.sample.simplepetrinet.model/model/simplepetrinet.ecore#//Place"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tokensSequence" upperBound="-1"
            eType="#//States/Place_tokens_Value" containment="true" eOpposite="#//States/Place_tokens_Value/parent"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
